// Autogenerated with DRAKON Editor 1.31


function console_If(msg: string | object, debug = true) {
    // item 37
    if (debug) {
        // item 39
        console.log(msg)
    } else {
        
    }
}

function range_Replace_In_Cells(range, regex, replacement:) {
    // item 45
      const sheet = range.getSheet()
      const values = range.getValues();
    // item 46
    // заменить в диапазоне по отдельным ячейкам
    // item 480001
    let row = 0;
    while (true) {
        // item 480002
        if (row < values.length) {
            
        } else {
            break;
        }
        // item 500001
        let col = 0;
        while (true) {
            // item 500002
            if (col < values[row].length) {
                
            } else {
                break;
            }
            // item 500003
            col++;
        }
        // item 52
        const cellValue = values[row][col].toString();
        // item 53
        if (cellValue.match(regex)) {
            // item 56
            sheet.getRange(row + 1, col + 1)
            	.setValue(cellValue
            	.replace(regex, replacement));
        } else {
            
        }
        // item 480003
        row++;
    }
}

function table_2_Map(table, column_Key, column_Item) {
    // item 18
    // таблицу массив из диапазона
    // в словарь
    // item 6
    var map = new Map();
    // item 70001
    let row = 0;
    while (true) {
        // item 70002
        if (row < table.length) {
            
        } else {
            break;
        }
        // item 9
        const key = table[row][column_Key];
        const item = table[row][column_Item];
        // item 10
        if ((key === undefined) || (item === undefined)) {
            
        } else {
            // item 16
            map.set(key, item);
        }
        // item 70003
        row++;
    }
    // item 17
    return map;
}

function table_2_Range(table, cell) {
    // item 28
    /** массив-таблицу в диапазон, начиная с ячейки */
    // item 25
    if (table.length > 0) {
        // item 24
        cell.offset(0, 0, table.length, table[0].length)
        	.setValues(table);
    } else {
        
    }
}



